#!/bin/bash


# *images
java7 -Xmx3g -jar dist/ASAP-Project.jar -p -tp 30 -fi "outputs/2015-task2/preprocess/STS.input.MSRvid-images.train.txt.features.arff" -fi "input/GensimTfidf/differencePhraseSTS.MSRvid-images.train.preprocessed.tsv" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2015-task2/simulation1/images/errors" -mt 4 -o "outputs/2015-task2/simulation1/images/predictions/STS.images-train.txt" -mo "outputs/2015-task2/simulation1/weka-models-images" -fo "outputs/2015-task2/simulation1/images/features-sts2014-images-train.txt" -tof "outputs/2015-task2/simulation1/images/preprocessed-images-train.txt" -llf "outputs/2015-task2/simulation1/images/LemmasNotFound-images-train.log" -lgf "outputs/2015-task2/simulation1/images/GrammarCounters-images-train.log" -lt -ltf "outputs/2015-task2/simulation1/images/Timings-images-train.log" -lner -lnerf "outputs/2015-task2/simulation1/images/NamedEntitiesFound-images-train.log" -ssaropiem | tee outputs/2015-task2/simulation1/run-images-train.log


# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -p -fi "outputs/2015-task2/preprocess/STS.input.headlines.all.train.txt.features.arff" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2015-task2/simulation1/headlines/errors" -mt 4 -o "outputs/2015-task2/simulation1/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2015-task2/simulation1/weka-models-headlines" -fo "outputs/2015-task2/simulation1/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2015-task2/simulation1/headlines/preprocessed-headlines-train.txt" -llf "outputs/2015-task2/simulation1/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2015-task2/simulation1/headlines/GrammarCounters-headlines-train.log" -lt -ltf "outputs/2015-task2/simulation1/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-train.log

# *headlines + SMTnews
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -i "input/STS.input.surprise.SMTnews.2012.test.txt;input/STS.gs.surprise.SMTnews.2012.test.txt" -i "input/STS.input.headlines.all.train.txt;input/STS.gs.headlines.all.train.txt" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines-SMTnews/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2015-task2/simulation1/headlines-SMTnews/errors" -mt 4 -o "outputs/2015-task2/simulation1/headlines-SMTnews/predictions/STS.headlines-train.txt" -mo "outputs/2015-task2/simulation1/weka-models-headlines-SMTnews" -fo "outputs/2015-task2/simulation1/headlines-SMTnews/features-sts2014-headlines-train.txt" -tof "outputs/2015-task2/simulation1/headlines-SMTnews/preprocessed-headlines-train.txt" -llf "outputs/2015-task2/simulation1/headlines-SMTnews/LemmasNotFound-headlines-train.log" -lgf "outputs/2015-task2/simulation1/headlines-SMTnews/GrammarCounters-headlines-train.log" -lt -ltf "outputs/2015-task2/simulation1/headlines-SMTnews/Timings-headlines-train.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines-SMTnews/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-SMTnews-train.log

# *headlines + deft-news
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -i "input/STS.input.deft-news.2014.test.txt;input/STS.gs.deft-news.2014.test.txt" -i "input/STS.input.headlines.all.train.txt;input/STS.gs.headlines.all.train.txt" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines-deft-news/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2015-task2/simulation1/headlines-deft-news/errors" -mt 4 -o "outputs/2015-task2/simulation1/headlines-deft-news/predictions/STS.headlines-train.txt" -mo "outputs/2015-task2/simulation1/weka-models-headlines-deft-news" -fo "outputs/2015-task2/simulation1/headlines-deft-news/features-sts2014-headlines-train.txt" -tof "outputs/2015-task2/simulation1/headlines-deft-news/preprocessed-headlines-train.txt" -llf "outputs/2015-task2/simulation1/headlines-deft-news/LemmasNotFound-headlines-train.log" -lgf "outputs/2015-task2/simulation1/headlines-deft-news/GrammarCounters-headlines-train.log" -lt -ltf "outputs/2015-task2/simulation1/headlines-deft-news/Timings-headlines-train.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines-deft-news/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-deft-news-train.log

# *headlines + deft-news + SMTnews
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -i "input/STS.input.surprise.SMTnews.2012.test.txt;input/STS.gs.surprise.SMTnews.2012.test.txt" -i "input/STS.input.deft-news.2014.test.txt;input/STS.gs.deft-news.2014.test.txt" -i "input/STS.input.headlines.all.train.txt;input/STS.gs.headlines.all.train.txt" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/errors" -mt 4 -o "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/predictions/STS.headlines-train.txt" -mo "outputs/2015-task2/simulation1/weka-models-headlines-SMTnews-deft-news" -fo "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/features-sts2014-headlines-train.txt" -tof "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/preprocessed-headlines-train.txt" -llf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/LemmasNotFound-headlines-train.log" -lgf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/GrammarCounters-headlines-train.log" -lt -ltf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/Timings-headlines-train.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-SMTnews-deft-news-train.log





##########################
##########################
##########################
# and evaluation:


# *headlines:
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.headlines.all.test.txt;input/STS.gs.headlines.all.test.txt" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines/LemmasFoundInDBP-headlines-test.log" -lpef "outputs/2015-task2/simulation1/headlines/errors/testing.log" -mt 4 -o "outputs/2015-task2/simulation1/headlines/predictions/STS.headlines-test.txt" -mi "outputs/2015-task2/simulation1/weka-models-headlines" -fo "outputs/2015-task2/simulation1/headlines/features-sts2014-headlines-test.txt" -tof "outputs/2015-task2/simulation1/headlines/preprocessed-headlines-test.txt" -llf "outputs/2015-task2/simulation1/headlines/LemmasNotFound-headlines-test.log" -lgf "outputs/2015-task2/simulation1/headlines/GrammarCounters-headlines-test.log" -lt -ltf "outputs/2015-task2/simulation1/headlines/Timings-headlines-test.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines/NamedEntitiesFound-headlines-test.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-test.log


# *headlines + SMTnews
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.headlines.all.test.txt;input/STS.gs.headlines.all.test.txt" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines-SMTnews/LemmasFoundInDBP-headlines-test.log" -lpef "outputs/2015-task2/simulation1/headlines-SMTnews/errors/testing.log" -mt 4 -o "outputs/2015-task2/simulation1/headlines-SMTnews/predictions/STS.headlines-test.txt" -mi "outputs/2015-task2/simulation1/weka-models-headlines-SMTnews" -fo "outputs/2015-task2/simulation1/headlines-SMTnews/features-sts2014-headlines-test.txt" -tof "outputs/2015-task2/simulation1/headlines-SMTnews/preprocessed-headlines-test.txt" -llf "outputs/2015-task2/simulation1/headlines-SMTnews/LemmasNotFound-headlines-test.log" -lgf "outputs/2015-task2/simulation1/headlines-SMTnews/GrammarCounters-headlines-test.log" -lt -ltf "outputs/2015-task2/simulation1/headlines-SMTnews/Timings-headlines-test.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines-SMTnews/NamedEntitiesFound-headlines-test.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-SMTnews-test.log

# *headlines + deft-news
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.headlines.all.test.txt;input/STS.gs.headlines.all.test.txt" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines-deft-news/LemmasFoundInDBP-headlines-test.log" -lpef "outputs/2015-task2/simulation1/headlines-deft-news/errors/testing.log" -mt 4 -o "outputs/2015-task2/simulation1/headlines-deft-news/predictions/STS.headlines-test.txt" -mi "outputs/2015-task2/simulation1/weka-models-headlines-deft-news" -fo "outputs/2015-task2/simulation1/headlines-deft-news/features-sts2014-headlines-test.txt" -tof "outputs/2015-task2/simulation1/headlines-deft-news/preprocessed-headlines-test.txt" -llf "outputs/2015-task2/simulation1/headlines-deft-news/LemmasNotFound-headlines-test.log" -lgf "outputs/2015-task2/simulation1/headlines-deft-news/GrammarCounters-headlines-test.log" -lt -ltf "outputs/2015-task2/simulation1/headlines-deft-news/Timings-headlines-test.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines-deft-news/NamedEntitiesFound-headlines-test.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-deft-news-test.log

# *headlines + deft-news + SMTnews
#java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.headlines.all.test.txt;input/STS.gs.headlines.all.test.txt"  -ll -lg -lt -lflf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/LemmasFoundInDBP-headlines-test.log" -lpef "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/errors/testing.log" -mt 4 -o "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/predictions/STS.headlines-test.txt" -mi "outputs/2015-task2/simulation1/weka-models-headlines-SMTnews-deft-news" -fo "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/features-sts2014-headlines-test.txt" -tof "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/preprocessed-headlines-test.txt" -llf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/LemmasNotFound-headlines-test.log" -lgf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/GrammarCounters-headlines-test.log" -lt -ltf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/Timings-headlines-test.log" -lner -lnerf "outputs/2015-task2/simulation1/headlines-SMTnews-deft-news/NamedEntitiesFound-headlines-test.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-headlines-SMTnews-deft-news-test.log


###################################
###################################
# other datasets (answers-forums, answers-students, belief)
#without distributional features
java7 -Xmx3g -jar dist/ASAP-Project.jar -p -fi "outputs/2015-task2/preprocess/STS.gs.all-but-headlines-MSRvid-images.train.txt.features.arff" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/others/LemmasFoundInDBP-others.log" -lpef "outputs/2015-task2/simulation1/others/errors" -mt 4 -o "outputs/2015-task2/simulation1/others/predictions/STS.others.txt" -mi "outputs/2015-task2/simulation1/weka-models-others" -fo "outputs/2015-task2/simulation1/others/features-sts2014-others.txt" -tof "outputs/2015-task2/simulation1/others/preprocessed-others.txt" -llf "outputs/2015-task2/simulation1/others/LemmasNotFound-others.log" -lgf "outputs/2015-task2/simulation1/others/GrammarCounters-others.log" -lt -ltf "outputs/2015-task2/simulation1/others/Timings-others.log" -lner -lnerf "outputs/2015-task2/simulation1/others/NamedEntitiesFound-others.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-others.log
#javalda default alpha and beta:
java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.all-but-headlines-MSRvid-images.train.txt;input/STS.gs.all-but-headlines-MSRvid-images.train.txt" -fi "input/JavaLDA/differencePhraseSTS.all-but-headlines-MSRvid-images.train.preprocessed.tsv" -fi "input/JavaLDA/euclideanDistanceSTS.all-but-headlines-MSRvid-images.train.preprocessed.tsv" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/others-JavaLDA/LemmasFoundInDBP-others-JavaLDA.log" -lpef "outputs/2015-task2/simulation1/others-JavaLDA/errors" -mt 4 -o "outputs/2015-task2/simulation1/others-JavaLDA/predictions/STS.others-JavaLDA.txt" -mi "outputs/2015-task2/simulation1/weka-models-others-JavaLDA" -fo "outputs/2015-task2/simulation1/others-JavaLDA/features-sts2014-others-JavaLDA.txt" -tof "outputs/2015-task2/simulation1/others-JavaLDA/preprocessed-others-JavaLDA.txt" -llf "outputs/2015-task2/simulation1/others-JavaLDA/LemmasNotFound-others-JavaLDA.log" -lgf "outputs/2015-task2/simulation1/others-JavaLDA/GrammarCounters-others-JavaLDA.log" -lt -ltf "outputs/2015-task2/simulation1/others-JavaLDA/Timings-others-JavaLDA.log" -lner -lnerf "outputs/2015-task2/simulation1/others-JavaLDA/NamedEntitiesFound-others-JavaLDA.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-others-JavaLDA.log
#GensimTfidf:
java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.all-but-headlines-MSRvid-images.train.txt;input/STS.gs.all-but-headlines-MSRvid-images.train.txt" -fi "input/GensimTfidf/differencePhraseSTS.all-but-headlines-MSRvid-images.train.preprocessed.tsv" -fi "input/GensimTfidf/euclideanDistanceSTS.all-but-headlines-MSRvid-images.train.preprocessed.tsv" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/others-GensimTfidf/LemmasFoundInDBP-others-GensimTfidf.log" -lpef "outputs/2015-task2/simulation1/others-GensimTfidf/errors" -mt 4 -o "outputs/2015-task2/simulation1/others-GensimTfidf/predictions/STS.others-GensimTfidf.txt" -mi "outputs/2015-task2/simulation1/weka-models-others-GensimTfidf" -fo "outputs/2015-task2/simulation1/others-GensimTfidf/features-sts2014-others-GensimTfidf.txt" -tof "outputs/2015-task2/simulation1/others-GensimTfidf/preprocessed-others-GensimTfidf.txt" -llf "outputs/2015-task2/simulation1/others-GensimTfidf/LemmasNotFound-others-GensimTfidf.log" -lgf "outputs/2015-task2/simulation1/others-GensimTfidf/GrammarCounters-others-GensimTfidf.log" -lt -ltf "outputs/2015-task2/simulation1/others-GensimTfidf/Timings-others-GensimTfidf.log" -lner -lnerf "outputs/2015-task2/simulation1/others-GensimTfidf/NamedEntitiesFound-others-GensimTfidf.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-others-GensimTfidf.log
#GensimNoTfidf:
java7 -Xmx3g -jar dist/ASAP-Project.jar -p -t "input/STS.input.all-but-headlines-MSRvid-images.train.txt;input/STS.gs.all-but-headlines-MSRvid-images.train.txt" -fi "input/GensimNoTfidf/differencePhraseSTS.all-but-headlines-MSRvid-images.train.preprocessed.tsv" -fi "input/GensimNoTfidf/euclideanDistanceSTS.all-but-headlines-MSRvid-images.train.preprocessed.tsv" -ll -lg -lt -lflf "outputs/2015-task2/simulation1/others-GensimNoTfidf/LemmasFoundInDBP-others-GensimNoTfidf.log" -lpef "outputs/2015-task2/simulation1/others-GensimNoTfidf/errors" -mt 4 -o "outputs/2015-task2/simulation1/others-GensimNoTfidf/predictions/STS.others-GensimNoTfidf.txt" -mi "outputs/2015-task2/simulation1/weka-models-others-GensimNoTfidf" -fo "outputs/2015-task2/simulation1/others-GensimNoTfidf/features-sts2014-others-GensimNoTfidf.txt" -tof "outputs/2015-task2/simulation1/others-GensimNoTfidf/preprocessed-others-GensimNoTfidf.txt" -llf "outputs/2015-task2/simulation1/others-GensimNoTfidf/LemmasNotFound-others-GensimNoTfidf.log" -lgf "outputs/2015-task2/simulation1/others-GensimNoTfidf/GrammarCounters-others-GensimNoTfidf.log" -lt -ltf "outputs/2015-task2/simulation1/others-GensimNoTfidf/Timings-others-GensimNoTfidf.log" -lner -lnerf "outputs/2015-task2/simulation1/others-GensimNoTfidf/NamedEntitiesFound-others-GensimNoTfidf.log" -ssaroplprev 1000000000000 | tee outputs/2015-task2/simulation1/run-others-GensimNoTfidf.log




grep "Best correlation" outputs/2015-task2/simulation1/*test.log | tee best-correlations-headlines-images.txt


