#!/bin/bash


# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha1beta1/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/errors" -mt 4 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha2beta05/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/errors" -mt 4 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alphabetadefault/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/errors" -mt 4 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/errors" -mt 4 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/errors" -mt 4 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha1beta1/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/errors" -mt 4 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha2beta05/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/errors" -mt 4 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alphabetadefault/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/errors" -mt 4 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/errors" -mt 4 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/errors" -mt 4 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha1beta1/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/errors" -mt 4 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha2beta05/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/errors" -mt 4 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alphabetadefault/differencePhraseSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/errors" -mt 4 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/errors" -mt 4 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/run-images-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/errors" -mt 4 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/run-images-train.log


grep "Best correlation =" outputs/2014-task10/simulation*-dist*/*.log | grep "eval" | tee outputs/2014-task10/dist-sims-bestcorrelations.log


