#!/bin/bash

#make sure all output directories are present
cat outputs_folder.list | xargs mkdir > /dev/null 2>&1


#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alpha1beta1/differencePhraseSTS.OnWN.train.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alpha1beta1/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/weka-models-OnWN" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alpha1beta1/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alpha1beta1/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/weka-models-headlines" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/headlines/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha1beta1/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha1beta1/run-images-train.log


####################################
#alpha2beta05
#############

java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alpha2beta05/differencePhraseSTS.OnWN.train.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alpha2beta05/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/weka-models-OnWN" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alpha2beta05/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alpha2beta05/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/weka-models-headlines" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/headlines/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha2beta05/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alpha2beta05/run-images-train.log


####################################
#alphabetadefault
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alphabetadefault/differencePhraseSTS.OnWN.train.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alphabetadefault/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/weka-models-OnWN" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alphabetadefault/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alphabetadefault/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/weka-models-headlines" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/headlines/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alphabetadefault/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-alphabetadefault/run-images-train.log


####################################
#GensimNoTfidf
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/weka-models-OnWN" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/weka-models-headlines" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/headlines/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimNoTfidf/run-images-train.log


####################################
#GensimTfidf
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/GensimTfidf/differencePhraseTOPICSSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/weka-models-OnWN" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/GensimTfidf/differencePhraseTOPICSSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/weka-models-headlines" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/headlines/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/weka-models-images" -fo "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaropiem | tee outputs/2014-task10/simulation4-dist-JavaLDA-GensimTfidf/run-images-train.log


################################################################################
################################################################################
################################################################################
################################################################################
##
##		simulation 5

################################################################################
################################################################################


####################################
#alpha1beta1
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alpha1beta1/differencePhraseSTS.OnWN.train.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alpha1beta1/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/weka-models-OnWN" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alpha1beta1/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alpha1beta1/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/weka-models-headlines" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha1beta1/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha1beta1/run-images-train.log


####################################
#alpha2beta05
#############

java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alpha2beta05/differencePhraseSTS.OnWN.train.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alpha2beta05/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/weka-models-OnWN" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alpha2beta05/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alpha2beta05/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/weka-models-headlines" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha2beta05/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alpha2beta05/run-images-train.log


####################################
#alphabetadefault
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alphabetadefault/differencePhraseSTS.OnWN.train.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alphabetadefault/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/weka-models-OnWN" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alphabetadefault/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alphabetadefault/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/weka-models-headlines" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alphabetadefault/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-alphabetadefault/run-images-train.log


####################################
#GensimNoTfidf
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/weka-models-OnWN" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/weka-models-headlines" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimNoTfidf/run-images-train.log


####################################
#GensimTfidf
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/GensimTfidf/differencePhraseTOPICSSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/weka-models-OnWN" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/GensimTfidf/differencePhraseTOPICSSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/weka-models-headlines" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/weka-models-images" -fo "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplpostv 1000000000000 | tee outputs/2014-task10/simulation5-dist-JavaLDA-GensimTfidf/run-images-train.log



################################################################################
################################################################################
################################################################################
################################################################################
##
##		simulation 6

################################################################################
################################################################################


####################################
#alpha1beta1
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alpha1beta1/differencePhraseSTS.OnWN.train.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alpha1beta1/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/weka-models-OnWN" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alpha1beta1/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alpha1beta1/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/weka-models-headlines" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha1beta1/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alpha1beta1/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha1beta1/run-images-train.log


####################################
#alpha2beta05
#############

java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alpha2beta05/differencePhraseSTS.OnWN.train.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alpha2beta05/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/weka-models-OnWN" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alpha2beta05/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alpha2beta05/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/weka-models-headlines" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alpha2beta05/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alpha2beta05/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alpha2beta05/run-images-train.log



####################################
#alphabetadefault
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/alphabetadefault/differencePhraseSTS.OnWN.train.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/alphabetadefault/differencePhraseSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/weka-models-OnWN" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/alphabetadefault/differencePhraseSTS.2013.headlines.preprocessed.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/alphabetadefault/differencePhraseSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/weka-models-headlines" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/alphabetadefault/differencePhraseSTS.2014.images.preprocessed.tsv" -fi "input/alphabetadefault/euclideanDistanceSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-alphabetadefault/run-images-train.log


####################################
#GensimNoTfidf
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/weka-models-OnWN" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/weka-models-headlines" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimNoTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimNoTfidf/run-images-train.log



####################################
#GensimTfidf
#############

#for *OnWN:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.OnWN.train.txt;input/STS.gs.OnWN.train.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.OnWN.train.tsv" -t "input/STS.input.OnWN.2014.txt;input/STS.gs.OnWN.2014.txt" -ft "input/GensimTfidf/differencePhraseTOPICSSTS.2014.OnWN.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/LemmasFoundInDBP-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/predictions/STS.OnWN.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/weka-models-OnWN" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/features-sts2014-OnWN-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/preprocessed-OnWN-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/LemmasNotFound-OnWN-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/GrammarCounters-OnWN-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/Timings-OnWN-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/OnWN/NamedEntitiesFound-OnWN-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/run-OnWN-train.log

# *headlines:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.headlines.2013.txt;input/STS.gs.headlines.2013.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2013.headlines.preprocessed.tsv" -t "input/STS.input.headlines.2014.txt;input/STS.gs.headlines.2014.txt" -ft "input/GensimTfidf/differencePhraseTOPICSSTS.2014.headlines.preprocessed.tsv" -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/LemmasFoundInDBP-headlines-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/predictions/STS.headlines-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/weka-models-headlines" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/features-sts2014-headlines-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/preprocessed-headlines-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/LemmasNotFound-headlines-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/GrammarCounters-headlines-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/headlines/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/run-headlines-train.log

# *images:
java7 -Xmx3g -jar dist/ASAP-Project.jar -i "input/STS.input.images.2014.txt;input/STS.gs.images.2014.txt" -fi "input/GensimTfidf/differencePhraseTOPICSSTS.2014.images.preprocessed.tsv" -tp 20 -lflf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/LemmasFoundInDBP-images-train.log" -lpef "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/errors" -p -mt 12 -o "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/predictions/STS.images-train.txt" -mo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/weka-models-images" -fo "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/features-sts2014-images-train.txt" -tof "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/preprocessed-images-train.txt" -llf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/LemmasNotFound-images-train.log" -lgf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/GrammarCounters-images-train.log" -ltf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/Timings-headlines-train.log" -lner -lnerf "outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/images/NamedEntitiesFound-headlines-train.log" -ssaroplprev 1000000000000 | tee outputs/2014-task10/simulation6-dist-JavaLDA-GensimTfidf/run-images-train.log


#get correlations:
grep "Best correlation =" outputs/2014-task10/simulation*-dist*/*.log | grep "eval" | tee outputs/2014-task10/dist-sims-bestcorrelations.log


