#!/bin/bash

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.answers-forums.2015.test.txt" -ft "input/GensimNoTfidf/differencePhraseSTS.answers-forums.2015.test.preprocessed.tsv" -ft "input/GensimNoTfidf/euclideanDistanceSTS.answers-forums.2015.test.preprocessed.tsv" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-all-but-headlines-MSRvid-images-GensimNoTfidf" -o "outputs/2015-task2/chosen/secondrun/answers-forums/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/secondrun/answers-forums/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/secondrun/answers-forums/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/secondrun/answers-forums/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/secondrun/run-answers-forums.log"

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.answers-students.2015.test.txt" -ft "input/GensimNoTfidf/differencePhraseSTS.answers-students.2015.test.preprocessed.tsv" -ft "input/GensimNoTfidf/euclideanDistanceSTS.answers-students.2015.test.preprocessed.tsv" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-all-but-headlines-MSRvid-images-GensimNoTfidf" -o "outputs/2015-task2/chosen/secondrun/answers-students/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/secondrun/answers-students/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/secondrun/answers-students/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/secondrun/answers-students/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/secondrun/run-answers-students.log"

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.belief.2015.test.txt" -ft "input/GensimNoTfidf/differencePhraseSTS.belief.2015.test.preprocessed.tsv" -ft "input/GensimNoTfidf/euclideanDistanceSTS.belief.2015.test.preprocessed.tsv" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-all-but-headlines-MSRvid-images-GensimNoTfidf" -o "outputs/2015-task2/chosen/secondrun/belief/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/secondrun/belief/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/secondrun/belief/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/secondrun/belief/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/secondrun/run-belief.log"




#third run::
java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.headlines.2015.test.txt" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-headlines-no-distributional-features" -o "outputs/2015-task2/chosen/thirdrun/headlines/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/thirdrun/headlines/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/thirdrun/headlines/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/thirdrun/headlines/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/thirdrun/run-headlines.log"

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.images.2015.test.txt" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-images-no-distributional-features" -o "outputs/2015-task2/chosen/thirdrun/images/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/thirdrun/images/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/thirdrun/images/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/thirdrun/images/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/thirdrun/run-images.log"

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.answers-forums.2015.test.txt" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-all-but-headlines-MSRvid-images-no-distributional-features" -o "outputs/2015-task2/chosen/thirdrun/answers-forums/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/thirdrun/answers-forums/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/thirdrun/answers-forums/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/thirdrun/answers-forums/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/thirdrun/run-answers-forums.log"

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.answers-students.2015.test.txt" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-all-but-headlines-MSRvid-images-no-distributional-features" -o "outputs/2015-task2/chosen/thirdrun/answers-students/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/thirdrun/answers-students/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/thirdrun/answers-students/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/thirdrun/answers-students/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/thirdrun/run-answers-students.log"

java7 -Xmx3g -jar dist/ASAP-Project.jar -t "input/STS.input.belief.2015.test.txt" -lt -lfl -mi "outputs/2015-task2/sim-ignore-exact-matches/weka-models-all-but-headlines-MSRvid-images-no-distributional-features" -o "outputs/2015-task2/chosen/thirdrun/belief/predictions/STS.test.txt" -p -mt 12 -fo "outputs/2015-task2/chosen/thirdrun/belief/features-sts2014-test.txt" -tof "outputs/2015-task2/chosen/thirdrun/belief/preprocessed-test.txt" -ltf "outputs/2015-task2/chosen/thirdrun/belief/Timings-test.log" -ssaropiem | tee "outputs/2015-task2/chosen/thirdrun/run-belief.log"

